# Generated by Django 5.0.7 on 2025-12-08 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applitravel", "0004_alter_voyage_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("IDCommande", models.AutoField(primary_key=True, serialize=False)),
                ("DateCommande", models.DateField()),
                ("Payee", models.BooleanField()),
                ("Prix", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "User_ID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "IDLigneCommande",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Quantite", models.IntegerField()),
                ("Prix", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "Commande_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ID_Commande",
                        to="applipanier.commande",
                    ),
                ),
                (
                    "Voyage_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ID_Voyage",
                        to="applitravel.voyage",
                    ),
                ),
            ],
        ),
    ]
