# Generated by Django 5.0.7 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicompte", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveluser",
            name="image",
            field=models.ImageField(
                default="imagesUsers/default.jpg", upload_to="imagesUsers"
            ),
        ),
    ]
