# Generated by Django 5.2.6 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('IDVille', models.AutoField(primary_key=True, serialize=False)),
                ('NomVille', models.CharField(max_length=50)),
                ('NomPays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('IDVoyage', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=50)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
