# Generated by Django 5.0.7 on 2025-09-15 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applitravel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Etape",
            fields=[
                ("IDEtape", models.AutoField(primary_key=True, serialize=False)),
                ("Nb_jours", models.CharField(max_length=50)),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applitravel.ville",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applitravel.voyage",
                    ),
                ),
            ],
            options={
                "unique_together": {("voyage", "ville")},
            },
        ),
    ]
