# Generated by Django 5.0.7 on 2025-10-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applitravel", "0002_etape"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyage",
            name="image",
            field=models.ImageField(
                default="imagesVoyages/default.png", upload_to="imagesVoyages"
            ),
        ),
    ]
