# Generated by Django 5.0.7 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applitravel", "0003_voyage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voyage",
            name="image",
            field=models.ImageField(
                default="imagesUsers/default.jpg", upload_to="images"
            ),
        ),
    ]
